-- Jalankan seluruh file ini di Supabase SQL Editor.
-- Akun login memakai email internal berbentuk username@kas-bendungan.id.

create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('developer', 'ketua', 'bendahara', 'anggota');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  role public.app_role not null default 'anggota',
  nik_ktp text,
  nik_kk text,
  nomor_hp text,
  warga_id bigint,
  created_at timestamptz not null default now()
);

create or replace function public.current_user_role()
returns public.app_role language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public
as $$ select public.current_user_role() in ('developer', 'ketua', 'bendahara') $$;

create table if not exists public.warga (id bigint generated by default as identity primary key, nama text not null, kelompok text not null, nik_kk text, nik_ktp text, alamat_rt text, nomor_telepon text, created_at timestamptz not null default now());
create table if not exists public.kelompok (id bigint generated by default as identity primary key, nama text not null unique, created_at timestamptz not null default now());
create table if not exists public.warga_kelompok (warga_id bigint not null references public.warga(id) on delete cascade, kelompok_id bigint not null references public.kelompok(id) on delete cascade, created_at timestamptz not null default now(), primary key (warga_id, kelompok_id));
create table if not exists public.profile_kelompok (profile_id uuid not null references public.profiles(id) on delete cascade, kelompok_id bigint not null references public.kelompok(id) on delete cascade, created_at timestamptz not null default now(), primary key (profile_id, kelompok_id));
create table if not exists public.iuran (id bigint generated by default as identity primary key, warga_id bigint references public.warga(id) on delete set null, bulan text not null, tanggal_bayar date not null default current_date, nominal numeric(14,2) not null check (nominal >= 0), keterangan text, created_at timestamptz not null default now());
create table if not exists public.pengeluaran (id bigint generated by default as identity primary key, tanggal date not null, keperluan text not null, nominal numeric(14,2) not null check (nominal >= 0), keterangan text, created_at timestamptz not null default now());
create table if not exists public.kartu_kas (id bigint generated by default as identity primary key, parent_id bigint references public.kartu_kas(id) on delete cascade, kategori text not null, nama text not null, catatan text not null default '', nominal numeric(14,2) not null default 0, ikon text not null default '+', urutan integer not null default 0, allow_tambah_anggota boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.audit_logs (id bigint generated by default as identity primary key, actor_id uuid references public.profiles(id) on delete set null, category text not null, action text not null, description text not null, entity text, entity_id text, created_at timestamptz not null default now());
create or replace function public.purge_old_audit_logs()
returns void language sql security definer set search_path = public
as $$ delete from public.audit_logs where created_at < now() - interval '1 year'; $$;
revoke all on function public.purge_old_audit_logs() from public;
grant execute on function public.purge_old_audit_logs() to service_role;
select public.purge_old_audit_logs();
create extension if not exists pg_cron with schema extensions;
select cron.unschedule(jobid) from cron.job where jobname = 'purge-old-audit-logs';
select cron.schedule('purge-old-audit-logs', '17 2 * * *', $$select public.purge_old_audit_logs();$$);
alter table public.kartu_kas add column if not exists allow_tambah_anggota boolean not null default false;
alter table public.iuran add column if not exists kartu_id bigint references public.kartu_kas(id) on delete set null;
alter table public.pengeluaran add column if not exists kartu_id bigint references public.kartu_kas(id) on delete set null;
alter table public.iuran add column if not exists petugas_id uuid references public.profiles(id) on delete set null default auth.uid();
alter table public.pengeluaran add column if not exists petugas_id uuid references public.profiles(id) on delete set null default auth.uid();
alter table public.audit_logs enable row level security;
drop policy if exists "staff read audit logs" on public.audit_logs;
create policy "staff read audit logs" on public.audit_logs for select to authenticated using (public.current_user_role() in ('developer','ketua','bendahara') and (public.current_user_role() = 'developer' or not exists (select 1 from public.profiles where id = audit_logs.actor_id and role = 'developer')));
create or replace function public.log_activity(p_category text, p_action text, p_description text, p_entity text default null, p_entity_id text default null) returns void language plpgsql security definer set search_path = public as $$ begin insert into public.audit_logs(actor_id, category, action, description, entity, entity_id) values (auth.uid(), left(trim(p_category), 80), left(trim(p_action), 80), left(trim(p_description), 500), left(nullif(trim(p_entity), ''), 120), left(nullif(trim(p_entity_id), ''), 120)); end; $$;
revoke all on function public.log_activity(text,text,text,text,text) from public;
grant execute on function public.log_activity(text,text,text,text,text) to authenticated;
create or replace function public.audit_row_change() returns trigger language plpgsql security definer set search_path = public as $$ declare row_id text; begin row_id := coalesce(to_jsonb(new)->>'id', to_jsonb(old)->>'id'); insert into public.audit_logs(actor_id, category, action, description, entity, entity_id) values (auth.uid(), case when tg_table_name in ('iuran','pengeluaran') then 'Transaksi' when tg_table_name in ('profiles','profile_kelompok') then 'Akun' when tg_table_name in ('kartu_kas','kelompok') then 'Kelompok' when tg_table_name = 'warga' then 'Anggota' else 'Data' end, tg_op, tg_op || ' pada ' || tg_table_name, tg_table_name, row_id); return coalesce(new, old); end; $$;
drop trigger if exists audit_iuran on public.iuran; create trigger audit_iuran after insert or update or delete on public.iuran for each row execute function public.audit_row_change();
drop trigger if exists audit_pengeluaran on public.pengeluaran; create trigger audit_pengeluaran after insert or update or delete on public.pengeluaran for each row execute function public.audit_row_change();
drop trigger if exists audit_profiles on public.profiles; create trigger audit_profiles after insert or update or delete on public.profiles for each row execute function public.audit_row_change();
drop trigger if exists audit_profile_kelompok on public.profile_kelompok; create trigger audit_profile_kelompok after insert or update or delete on public.profile_kelompok for each row execute function public.audit_row_change();
drop trigger if exists audit_kartu_kas on public.kartu_kas; create trigger audit_kartu_kas after insert or update or delete on public.kartu_kas for each row execute function public.audit_row_change();
drop trigger if exists audit_kelompok on public.kelompok; create trigger audit_kelompok after insert or update or delete on public.kelompok for each row execute function public.audit_row_change();
drop trigger if exists audit_warga on public.warga; create trigger audit_warga after insert or update or delete on public.warga for each row execute function public.audit_row_change();
drop trigger if exists audit_warga_kelompok on public.warga_kelompok; create trigger audit_warga_kelompok after insert or update or delete on public.warga_kelompok for each row execute function public.audit_row_change();
alter table public.iuran alter column warga_id drop not null;
alter table public.iuran drop constraint if exists iuran_warga_id_fkey;
alter table public.iuran add constraint iuran_warga_id_fkey foreign key (warga_id) references public.warga(id) on delete set null;
create or replace function public.sync_root_card_to_group() returns trigger language plpgsql security definer set search_path = public as $$ begin if new.parent_id is null and nullif(trim(new.nama), '') is not null then insert into public.kelompok (nama) values (trim(new.nama)) on conflict (nama) do nothing; end if; return new; end; $$;
drop trigger if exists sync_root_card_to_group on public.kartu_kas;
create trigger sync_root_card_to_group after insert or update of nama, parent_id on public.kartu_kas for each row execute function public.sync_root_card_to_group();

alter table public.profiles enable row level security;
alter table public.warga enable row level security;
alter table public.kelompok enable row level security;
alter table public.warga_kelompok enable row level security;
alter table public.profile_kelompok enable row level security;
alter table public.iuran enable row level security;
alter table public.pengeluaran enable row level security;
alter table public.kartu_kas enable row level security;

drop policy if exists "profiles own or developer read" on public.profiles;
drop policy if exists "profiles_own_or_staff_read" on public.profiles;
create policy "profiles_own_or_staff_read" on public.profiles for select to authenticated using (id = auth.uid() or (public.current_user_role() = 'developer') or (role <> 'developer' and public.current_user_role() in ('ketua','bendahara','anggota')));
drop policy if exists "staff manage profiles" on public.profiles;
drop policy if exists "staff update profiles" on public.profiles;
drop policy if exists "staff insert profiles" on public.profiles;
drop policy if exists "developer manage profiles" on public.profiles;
drop policy if exists "developer_manage_profiles" on public.profiles;
create policy "staff update profiles" on public.profiles for update to authenticated using (public.current_user_role() = 'developer' or (public.current_user_role() = 'ketua' and role <> 'developer') or (public.current_user_role() = 'bendahara' and (role = 'anggota' or id = auth.uid()))) with check (public.current_user_role() = 'developer' or (public.current_user_role() = 'ketua' and role <> 'developer') or (public.current_user_role() = 'bendahara' and (role = 'anggota' or (id = auth.uid() and role = 'bendahara'))));
create policy "staff insert profiles" on public.profiles for insert to authenticated with check (public.current_user_role() = 'developer' or (public.current_user_role() = 'ketua' and role <> 'developer') or (public.current_user_role() = 'bendahara' and role = 'anggota'));

-- Semua akun terautentikasi dapat melihat data. Hanya developer/ketua/bendahara dapat mengubahnya.
create or replace function public.apply_data_policies(target regclass) returns void language plpgsql security definer as $$ begin execute format('drop policy if exists "authenticated read" on %s', target); execute format('create policy "authenticated read" on %s for select to authenticated using (true)', target); execute format('drop policy if exists "staff insert" on %s', target); execute format('create policy "staff insert" on %s for insert to authenticated with check (public.is_staff())', target); execute format('drop policy if exists "staff update" on %s', target); execute format('create policy "staff update" on %s for update to authenticated using (public.is_staff()) with check (public.is_staff())', target); execute format('drop policy if exists "staff delete" on %s', target); execute format('create policy "staff delete" on %s for delete to authenticated using (public.is_staff())', target); end $$;
select public.apply_data_policies('public.warga');
select public.apply_data_policies('public.iuran');
select public.apply_data_policies('public.pengeluaran');
select public.apply_data_policies('public.kartu_kas');
drop function public.apply_data_policies(regclass);

insert into public.kelompok (nama) values ('Pemuda'), ('Umum') on conflict (nama) do nothing;
drop policy if exists "authenticated read kelompok" on public.kelompok;
create policy "authenticated read kelompok" on public.kelompok for select to authenticated using (true);
drop policy if exists "staff manage kelompok" on public.kelompok;
create policy "staff manage kelompok" on public.kelompok for all to authenticated using (public.is_staff()) with check (public.is_staff());
drop policy if exists "authenticated read warga kelompok" on public.warga_kelompok;
create policy "authenticated read warga kelompok" on public.warga_kelompok for select to authenticated using (true);
drop policy if exists "staff manage warga kelompok" on public.warga_kelompok;
create policy "staff manage warga kelompok" on public.warga_kelompok for all to authenticated using (public.is_staff()) with check (public.is_staff());
drop policy if exists "authenticated read profile kelompok" on public.profile_kelompok;
create policy "authenticated read profile kelompok" on public.profile_kelompok for select to authenticated using (true);
drop policy if exists "staff manage profile kelompok" on public.profile_kelompok;
create policy "staff manage profile kelompok" on public.profile_kelompok for all to authenticated using (public.is_staff()) with check (public.is_staff());

create or replace function public.create_account(p_username text, p_display_name text, p_password text, p_role public.app_role)
returns uuid language plpgsql security definer set search_path = public, auth, extensions as $$
declare new_id uuid; normalized text := lower(trim(p_username));
begin
  if public.current_user_role() not in ('developer', 'ketua', 'bendahara') then raise exception 'Hanya pengelola akun yang dapat membuat akun'; end if;
  if public.current_user_role() = 'bendahara' and p_role <> 'anggota' then raise exception 'Bendahara hanya dapat membuat akun anggota'; end if;
  if public.current_user_role() = 'ketua' and p_role = 'developer' then raise exception 'Ketua hanya dapat membuat akun bendahara atau anggota'; end if;
  if normalized = '' or length(p_password) < 8 or trim(p_display_name) = '' then raise exception 'Data akun tidak valid'; end if;
  if exists (select 1 from public.profiles where lower(username) = normalized) or exists (select 1 from auth.users where lower(email) = normalized || '@kas-bendungan.id') then raise exception 'Username sudah digunakan'; end if;
  new_id := gen_random_uuid();
  insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone, phone_change, phone_change_token, reauthentication_token, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
  values ('00000000-0000-0000-0000-000000000000', new_id, 'authenticated', 'authenticated', normalized || '@kas-bendungan.id', crypt(p_password, gen_salt('bf')), now(), '', '', '', '', '', null, '', '', '', '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('username', trim(p_username), 'display_name', trim(p_display_name)), now(), now());
  insert into auth.identities (provider_id, user_id, identity_data, provider, created_at, updated_at) values (new_id::text, new_id, jsonb_build_object('sub', new_id::text, 'email', normalized || '@kas-bendungan.id'), 'email', now(), now());
  insert into public.profiles (id, username, display_name, role) values (new_id, trim(p_username), trim(p_display_name), p_role);
  return new_id;
end; $$;
revoke all on function public.create_account(text,text,text,public.app_role) from public;
grant execute on function public.create_account(text,text,text,public.app_role) to authenticated;

-- Akun developer awal. Aman dijalankan ulang karena upsert berbasis username.
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current, phone, phone_change, phone_change_token, reauthentication_token, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
select '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', 'capik@kas-bendungan.id', crypt('@Capik190989', gen_salt('bf')), now(), '', '', '', '', '', null, '', '', '', '{"provider":"email","providers":["email"]}'::jsonb, '{"username":"Capik","display_name":"Capik"}'::jsonb, now(), now()
where not exists (select 1 from auth.users where email = 'capik@kas-bendungan.id');

insert into public.profiles (id, username, display_name, role)
select id, 'Capik', 'Capik', 'developer'::public.app_role from auth.users where email = 'capik@kas-bendungan.id'
on conflict (username) do update set role = excluded.role, display_name = excluded.display_name;

-- Contoh penambahan akun lain setelah dibuat di Authentication > Users:
-- insert into public.profiles (id, username, display_name, role) values ('UUID_USER', 'namauser', 'Nama User', 'anggota');
