create table if not exists public.warga (
  id bigint generated by default as identity primary key,
  nama text not null,
  kelompok text not null,
  nik_kk text,
  nik_ktp text,
  alamat_rt text,
  nomor_telepon text,
  created_at timestamptz not null default now()
);

create table if not exists public.iuran (
  id bigint generated by default as identity primary key,
  warga_id bigint not null references public.warga(id) on delete restrict,
  bulan text not null,
  tanggal_bayar date not null default current_date,
  nominal numeric(14,2) not null check (nominal >= 0),
  keterangan text,
  created_at timestamptz not null default now()
);

create table if not exists public.pengeluaran (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  keperluan text not null,
  nominal numeric(14,2) not null check (nominal >= 0),
  keterangan text,
  created_at timestamptz not null default now()
);

alter table public.warga enable row level security;
alter table public.iuran enable row level security;
alter table public.pengeluaran enable row level security;

drop policy if exists "Public can read warga" on public.warga;
drop policy if exists "Public can insert warga" on public.warga;
drop policy if exists "Public can read iuran" on public.iuran;
drop policy if exists "Public can insert iuran" on public.iuran;
drop policy if exists "Public can read pengeluaran" on public.pengeluaran;
drop policy if exists "Public can insert pengeluaran" on public.pengeluaran;

create policy "Public can read warga" on public.warga for select using (true);
create policy "Public can insert warga" on public.warga for insert with check (true);

create policy "Public can read iuran" on public.iuran for select using (true);
create policy "Public can insert iuran" on public.iuran for insert with check (true);

create policy "Public can read pengeluaran" on public.pengeluaran for select using (true);
create policy "Public can insert pengeluaran" on public.pengeluaran for insert with check (true);
