"use client";

import { ReactNode, useEffect, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import LoginScreen from "@/components/login-screen";
import { roleLabel, useAuth } from "@/lib/auth";

const menuItems = [["⌂", "Dashboard", "Ringkasan kas kampung", "/"], ["▣", "Catatan transaksi", "Pemasukan & pengeluaran", "/iuran"], ["♙", "Data Anggota", "Daftar Semua Anggota", "/warga"], ["◒", "Laporan", "Rekap transparansi kas", "/riwayat"], ["⚙", "Pengaturan", "Backup dan data Excel", "/pengaturan"], ["◐", "Tema", "Warna dan tampilan", "#tema"]] as const;
const themes = [["light", "Terang"], ["dark", "Gelap"], ["blue", "Biru"], ["blue-white", "Biru putih"], ["blue-black", "Biru hitam"], ["pink", "Pink"], ["pink-white", "Pink putih"], ["pink-black", "Pink hitam"]] as const;

export default function SiteChrome({ children }: { children: ReactNode }) {
  const router = useRouter(); const pathname = usePathname(); const { user, profile, loading, signOut, canManageAccounts } = useAuth();
  const [drawerOpen, setDrawerOpen] = useState(false); const [theme, setTheme] = useState("light"); const [themeSettingsOpen, setThemeSettingsOpen] = useState(false);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { const saved = window.localStorage.getItem("kas-bendungan-theme"); if (saved && themes.some(([value]) => value === saved)) setTheme(saved); }, []);
  useEffect(() => { window.localStorage.setItem("kas-bendungan-theme", theme); }, [theme]);
  if (loading) return <main className="login-shell"><p className="login-loading">Menghubungkan ke Supabase...</p><span className="login-footer-credit">© 2026 Kas Desa - By Capik</span></main>;
  if (!user || !profile) return <LoginScreen />;
  function selectMenu(path: string) { if (path === "#tema") { setThemeSettingsOpen((open) => !open); return; } router.push(path); setDrawerOpen(false); }
  const activeMenu = pathname === "/" ? "Dashboard" : pathname === "/iuran" || pathname === "/pengeluaran" ? "Catatan transaksi" : pathname === "/warga" ? "Data Anggota" : pathname === "/riwayat" ? "Laporan" : pathname === "/pengaturan" ? "Pengaturan" : pathname === "/user" ? "User" : "";
  return <div className={`site-chrome theme-${theme}`}><header className="app-header"><button className="village-logo" onClick={() => setDrawerOpen(true)} aria-label="Buka menu"><img src="/logo-pemuda-desa-wangon-mas.png" alt="Logo Pemuda Desa Wangon Mas" /></button><button className="header-title header-home-button" onClick={() => router.push("/")}><h1>Kas Wangon Mas.<br />Desa Bendungan</h1><p className="header-copy">Satu ruang sederhana untuk melihat, mengatur, dan menjaga kas warga bersama-sama.</p></button></header><div className="site-content">{children}</div><footer className="dashboard-footer"><div className="footer-tip"><b>Ruang bersama</b><span>Catatan kas yang rapi membuat desa makin berarti.</span></div><span className="footer-credit">© 2026 Kas Desa - By Capik</span></footer>{drawerOpen && <div className="drawer-backdrop" onClick={() => setDrawerOpen(false)} />}<aside className={`drawer ${drawerOpen ? "open" : ""}`} aria-hidden={!drawerOpen}><div className="drawer-head"><div className="drawer-brand"><img className="sidebar-logo" src="/logo-pemuda-desa-wangon-mas.png" alt="Logo" /><span>Kas<br /><b>Wangon Mas</b></span></div><button onClick={() => setDrawerOpen(false)} className="close-drawer" aria-label="Tutup menu">×</button></div><div className="profile-card"><div className="avatar">{profile.username.slice(0, 2).toUpperCase()}</div><div className="profile-copy"><b>{profile.username}</b><span>{roleLabel(profile.role)}</span></div><button className="profile-logout" onClick={() => void signOut()} aria-label="Keluar dari akun" title="Keluar dari akun">↪</button></div><nav className="drawer-nav">{menuItems.map(([icon, label, detail, path]) => <button key={label} className={activeMenu === label ? "selected" : ""} onClick={() => selectMenu(path)}><span className="nav-icon">{icon}</span><span><b>{label}</b><small>{detail}</small></span>{activeMenu === label && <i>•</i>}</button>)}{canManageAccounts && <button className={activeMenu === "User" ? "selected" : ""} onClick={() => selectMenu("/user")}><span className="nav-icon">◎</span><span><b>User</b><small>{profile.role === "developer" ? "Tambah dan kelola akun" : profile.role === "ketua" ? "Kelola akun non-developer" : "Lihat akun pengguna"}</small></span>{activeMenu === "User" && <i>•</i>}</button>}</nav>{themeSettingsOpen && <section className="theme-settings"><div className="theme-settings-title"><b>Tema tampilan</b><small>Pilih warna yang nyaman dibaca</small></div><div className="theme-options">{themes.map(([value, label]) => <button key={value} type="button" className={`theme-option ${theme === value ? "selected" : ""}`} onClick={() => setTheme(value)}>{label}</button>)}</div></section>}<div className="drawer-slogan"><b>Ruang bersama</b><span>Catatan kas yang rapi membuat desa makin berarti.</span><small>© 2026 Kas Desa - By Capik</small></div></aside></div>;
}
