-- Reusable groups with many-to-many membership for accounts and warga.
create table if not exists public.kelompok (
  id bigint generated by default as identity primary key,
  nama text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.warga_kelompok (
  warga_id bigint not null references public.warga(id) on delete cascade,
  kelompok_id bigint not null references public.kelompok(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (warga_id, kelompok_id)
);

create table if not exists public.profile_kelompok (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  kelompok_id bigint not null references public.kelompok(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, kelompok_id)
);

insert into public.kelompok (nama)
values ('Pemuda'), ('Umum')
on conflict (nama) do nothing;

-- Preserve existing single-group warga data in the new relation.
insert into public.kelompok (nama)
select distinct trim(kelompok) from public.warga
where nullif(trim(kelompok), '') is not null
on conflict (nama) do nothing;

insert into public.warga_kelompok (warga_id, kelompok_id)
select w.id, k.id
from public.warga w
join public.kelompok k on k.nama = trim(w.kelompok)
where nullif(trim(w.kelompok), '') is not null
on conflict do nothing;

alter table public.kelompok enable row level security;
alter table public.warga_kelompok enable row level security;
alter table public.profile_kelompok enable row level security;

drop policy if exists "authenticated read kelompok" on public.kelompok;
create policy "authenticated read kelompok" on public.kelompok for select to authenticated using (true);
drop policy if exists "staff manage kelompok" on public.kelompok;
create policy "staff manage kelompok" on public.kelompok for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "authenticated read warga kelompok" on public.warga_kelompok;
create policy "authenticated read warga kelompok" on public.warga_kelompok for select to authenticated using (true);
drop policy if exists "staff manage warga kelompok" on public.warga_kelompok;
create policy "staff manage warga kelompok" on public.warga_kelompok for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "authenticated read profile kelompok" on public.profile_kelompok;
create policy "authenticated read profile kelompok" on public.profile_kelompok for select to authenticated using (true);
drop policy if exists "staff manage profile kelompok" on public.profile_kelompok;
create policy "staff manage profile kelompok" on public.profile_kelompok for all to authenticated using (public.is_staff()) with check (public.is_staff());
